#!/sbin/openrc-run

name="mercure"
description="Mercure - Server-sent live updates"
command="/usr/bin/mercure"
command_args="-config /etc/mercure/Caddyfile"
command_background=true
pidfile="/run/mercure/mercure.pid"
command_user="mercure:mercure"
supervisor=supervise-daemon

output_log="/var/log/mercure/mercure.log"
error_log="/var/log/mercure/mercure_err.log"

depend() {
    need net
    after firewall
}
